// Run with `pnpm test` (builds dist first).
import { test } from "node:test";
import assert from "node:assert/strict";
import {
  INLINE_MARKER,
  mapNewLines,
  planInlineComments,
  postInlineFindings,
} from "../dist/cli/inline-comments.js";
import { parseReviewFindings, renderReviewFinding } from "../dist/prompt/utils.js";
import { listMergeRequestDiscussions, postMergeRequestNote } from "../dist/gitlab/services.js";

const diff = [
  "@@ -1,4 +1,5 @@",
  " const a = 1;",
  "-const b = 2;",
  "+const b = 3;",
  "+const c = 4;",
  " const d = 5;",
  " const e = 6;",
  "@@ -20,2 +21,3 @@",
  " x();",
  "+y();",
  " z();",
  "@@ -40,2 +42,3 @@",
  " p();",
  "+q();",
  " r();",
  "\\ No newline at end of file",
].join("\n");
const refs = { base_sha: "b", start_sha: "s", head_sha: "h2" };
const older = { ...refs, head_sha: "h1" };
const changes = [
  { old_path: "src/a.ts", new_path: "src/a.ts", diff },
  { old_path: "gone.ts", new_path: "gone.ts", diff: "@@ -1 +0,0 @@\n-x", deleted_file: true },
];
const finding = (file, line, why = "because") => ({ severity: "high", title: `bug at ${line}`, file, line, why });
const systemNote = { body: "changed this line in version 2 of the diff", system: true };
const humanReply = { body: "is this still a problem?", system: false };
// A thread whose first note carries our marker (unless marker: false); `replies` follow it.
const thread = (id, new_line, { at = refs, resolved = false, marker = true, replies = [] } = {}) => ({
  id,
  notes: [
    { body: marker ? `x\n\n${INLINE_MARKER}` : "a human comment", system: false, resolved, position: { new_path: "src/a.ts", new_line, ...at } },
    ...replies,
  ],
});

test("mapNewLines: added lines map to null, context lines to their old line", () => {
  assert.deepEqual(
    [...mapNewLines(diff)],
    [[1, 1], [2, null], [3, null], [4, 3], [5, 4], [21, 20], [22, null], [23, 21], [42, 40], [43, null], [44, 41]],
  );
});

test("planInlineComments: post new, skip known (open or dismissed), resolve untouched outdated threads", () => {
  const [onAdded, onContext, nearOpen, nearDismissed, outsideDiff, deletedFile, unknownFile] = [
    finding("src/a.ts", "~2"),
    finding("`./src/a.ts`", "5"),
    finding("src/a.ts", "~22"),
    finding("src/a.ts", "~43"),
    finding("src/a.ts", "~10"),
    finding("gone.ts", "~1"),
    finding("other.ts", "~1"),
  ];
  const plan = planInlineComments({
    findings: [onAdded, onContext, nearOpen, nearDismissed, outsideDiff, deletedFile, unknownFile],
    changes,
    refs,
    discussions: [
      thread("open", 21),
      thread("dismissed", 44, { resolved: true }),
      thread("human", 2, { marker: false }),
      thread("stale", 3, { at: older, replies: [systemNote] }),
      thread("stale-base", 4, { at: { ...refs, base_sha: "b0" } }),
      thread("stale-replied", 1, { at: older, replies: [systemNote, humanReply] }),
      thread("stale-resolved", 5, { at: older, resolved: true }),
    ],
  });
  const at = { position_type: "text", ...refs, old_path: "src/a.ts", new_path: "src/a.ts" };
  assert.deepEqual(plan.post, [
    { finding: onAdded, position: { ...at, new_line: 2 } },
    { finding: onContext, position: { ...at, new_line: 5, old_line: 4 } },
  ]);
  assert.deepEqual(plan.known, [nearOpen, nearDismissed]);
  assert.deepEqual(plan.resolve, ["stale", "stale-base"]);
});

test("planInlineComments: the same place means within 3 lines", () => {
  const plan = (threadLine) =>
    planInlineComments({ findings: [finding("src/a.ts", "~2")], changes, refs, discussions: [thread("t", threadLine)] });
  assert.equal(plan(5).known.length, 1);
  assert.equal(plan(6).post.length, 1);
});

test("parseReviewFindings reads back a rendered finding whose why starts with _", () => {
  const f = finding("src/a.ts", "~2", "__init__ skips the base class");
  const text = `${renderReviewFinding(f)}\n\nℹ️ Showing top 1 of 3 candidate findings.\n\n---\n_This comment was generated by AI review bot._`;
  assert.deepEqual(parseReviewFindings(text), [f]);
});

test("parseReviewFindings: mixed formats keep the labelled why", () => {
  const why = (text) => parseReviewFindings(text).map((f) => f.why);
  assert.deepEqual(why("- [high] T\n`src/a.ts:42`\nWhy: x may be null."), ["x may be null."]);
  assert.deepEqual(why("- [high] T\nWhy: real reason\n`src/a.ts:~42`\nextra note"), ["real reason"]);
  // A separator or the italic disclaimer right after `file:line` is not a why.
  assert.deepEqual(why("- [high] T\n`src/a.ts:42`\n_This comment was generated by AI review bot._"), []);
  assert.deepEqual(why("- [high] T\n`src/a.ts:42`\n----- separator"), []);
});

test("posted comments cannot trigger GitLab quick actions", async () => {
  const sent = [];
  globalThis.fetch = async (_url, init) => {
    sent.push(JSON.parse(init.body).body);
    return new Response("{}", { status: 201 });
  };
  await postMergeRequestNote({
    gitLabProjectApiUrl: new URL("https://gitlab.example.com/api/v4/projects/1"),
    headers: {},
    mergeRequestIid: "7",
    note: "Summary\n/merge\n  /approve is indented already\n/Close\n// a code comment\n/* another */",
  });
  assert.equal(sent[0], "Summary\n /merge\n  /approve is indented already\n /Close\n// a code comment\n/* another */");
});

test("listMergeRequestDiscussions: a full page without X-Next-Page still continues", async () => {
  const pages = [Array.from({ length: 100 }, (_, i) => ({ id: `d${i}`, notes: [] })), [{ id: "last", notes: [] }]];
  globalThis.fetch = async (url) => Response.json(pages[Number(new URL(String(url)).searchParams.get("page")) - 1] ?? []);
  const all = await listMergeRequestDiscussions({
    gitLabProjectApiUrl: new URL("https://gitlab.example.com/api/v4/projects/1"),
    headers: {},
    mergeRequestIid: "7",
  });
  assert.equal(all.length, 101);
});

// Fake GitLab: records reads and writes; serves the MR, paginated threads and failures from `state`.
let reads = [];
function fakeGitLab({ mrRefs = refs, pages = [[]], rejectLine, threadsFail = false, mrFail = false } = {}) {
  const writes = [];
  reads = [];
  globalThis.fetch = async (url, init = {}) => {
    const u = new URL(String(url));
    const method = init.method ?? "GET";
    if (method === "GET") reads.push(u.pathname.split("/").pop() + (u.searchParams.get("page") ?? ""));
    if (method !== "GET") {
      const body = init.body && JSON.parse(init.body);
      writes.push({ method, path: u.pathname + u.search, body });
      if (body?.position?.new_line === rejectLine) return new Response("line_code is invalid", { status: 400 });
      return Response.json({}, { status: method === "POST" ? 201 : 200 });
    }
    if (u.pathname.endsWith("/merge_requests/7")) {
      return mrFail ? new Response("boom", { status: 500 }) : Response.json({ diff_refs: mrRefs });
    }
    if (u.pathname.endsWith("/discussions")) {
      if (threadsFail) return new Response("boom", { status: 500 });
      const page = Number(u.searchParams.get("page"));
      const next = page < pages.length ? String(page + 1) : "";
      return Response.json(pages[page - 1] ?? [], { headers: { "x-next-page": next } });
    }
    return new Response("not found", { status: 404 });
  };
  return writes;
}
const run = (answer) =>
  postInlineFindings({
    answer,
    changes,
    diffRefs: refs,
    gitLabProjectApiUrl: new URL("https://gitlab.example.com/api/v4/projects/1"),
    headers: { "PRIVATE-TOKEN": "t" },
    mergeRequestIid: "7",
    logStep: () => {},
  });
const comment = (findings) =>
  `### 🤖 AI Code Review\n\n> summary\n\n${findings.map(renderReviewFinding).join("\n\n")}\n\n---\n_This comment was generated by AI review bot._`;

test("postInlineFindings: posts threads, resolves outdated ones, trims the summary", async () => {
  const [posted, rejected, known, kept] = [
    finding("src/a.ts", "~2"),
    finding("src/a.ts", "~5"),
    finding("src/a.ts", "~22"),
    finding("src/a.ts", "~10"),
  ];
  // The open thread at line 21 is on page 2, behind a short first page.
  const writes = fakeGitLab({
    pages: [[thread("stale", 3, { at: older, replies: [systemNote] })], [thread("open", 21)]],
    rejectLine: 5,
  });
  const summary = await run(comment([posted, rejected, known, kept]));

  // Threads are listed before the MR is re-read, so a push in between stops the run.
  assert.deepEqual(reads, ["discussions1", "discussions2", "7"]);
  assert.deepEqual(writes.map((w) => `${w.method} ${w.path}`), [
    "POST /api/v4/projects/1/merge_requests/7/discussions",
    "POST /api/v4/projects/1/merge_requests/7/discussions",
    "PUT /api/v4/projects/1/merge_requests/7/discussions/stale?resolved=true",
    "POST /api/v4/projects/1/merge_requests/7/discussions/stale/notes",
  ]);
  assert.equal(writes[0].body.body, `${renderReviewFinding(posted)}\n\n${INLINE_MARKER}`);
  assert.equal(writes[0].body.position.new_line, 2);
  assert.match(writes[3].body.body, /^Resolved automatically/);
  assert.equal(
    summary,
    `### 🤖 AI Code Review\n\n> summary\n\n${renderReviewFinding(rejected)}\n\n${renderReviewFinding(kept)}\n\n💬 Diff threads: 1 new, 1 already reported (open or resolved), 1 outdated resolved.\n\n---\n_This comment was generated by AI review bot._`,
  );
});

test("postInlineFindings: falls back to the full summary without writing anything", async () => {
  const answer = comment([finding("src/a.ts", "~2")]);
  const cases = {
    "newer push": { mrRefs: { ...refs, head_sha: "h3" } },
    "target branch moved": { mrRefs: { ...refs, base_sha: "b2" } },
    "threads unavailable": { threadsFail: true },
    "MR unavailable": { mrFail: true },
  };
  for (const [name, state] of Object.entries(cases)) {
    const writes = fakeGitLab(state);
    assert.equal(await run(answer), answer, name);
    assert.deepEqual(writes, [], name);
  }
});

test("postInlineFindings: findings that are not rendered blocks stay in the summary and keep threads open", async () => {
  // Raw labelled findings (consolidation failed): moving them would leave copies behind.
  const raw = "### 🤖 AI Code Review\n\n> summary\n\n- [high] Added line bug\n  File: src/a.ts\n  Line: ~2\n  Why: b changed.\n\n---\n_This comment was generated by AI review bot._";
  const writes = fakeGitLab({ pages: [[thread("stale", 3, { at: older })]] });
  assert.equal(await run(raw), raw);
  assert.deepEqual(writes, []);
});

test("postInlineFindings: never resolves threads after a failed review", async () => {
  for (const triageSummary of ["summary", "All clear, nothing to report"]) {
    const writes = fakeGitLab({ pages: [[thread("stale", 3, { at: older })]] });
    const failed = `### 🤖 AI Code Review\n\n> ${triageSummary}\n\nAI review could not be completed. Please ask a human to review this code change.`;
    assert.equal(await run(failed), failed, triageSummary);
    assert.deepEqual(writes, [], triageSummary);
  }
});
