import type { ChatCompletionMessageParam, ChatCompletion } from 'openai/resources/index.mjs'
import type { OldFileVersion } from '../gitlab/services.js'

export interface PromptLimits {
  maxOldFiles: number
  maxOldFileChars: number
  maxDiffs: number
  maxDiffChars: number
  maxTotalPromptChars: number
}

export const DEFAULT_PROMPT_LIMITS: PromptLimits = {
  maxOldFiles: 30,
  maxOldFileChars: 12000,
  maxDiffs: 50,
  maxDiffChars: 16000,
  maxTotalPromptChars: 220000
}

function truncateWithMarker (value: string, maxChars: number, markerLabel: string): string {
  if (value.length <= maxChars) return value
  const omitted = value.length - maxChars
  return `${value.slice(0, maxChars)}\n\n[... ${markerLabel} truncated, omitted ${omitted} chars ...]`
}

const QUESTIONS = `\n\nQuestions:\n
1. Can you summarize the changes in a succinct bullet point list\n
2. In the diff, are the added or changed code written in a clear and easy to understand way?\n
3. Does the code use comments, or descriptive function and variables names that explain what they mean?\n
4. based on the code complexity of the changes, could the code be simplified without breaking its functionality? if so can you give example snippets?\n
5. Can you find any bugs, if so please explain and reference line numbers?\n
6. Do you see any code that could induce security issues?\n\n`

const MESSAGES: ChatCompletionMessageParam[] = [{
  role: 'system',
  content: 'You are a senior developer reviewing code changes. Format the response so it renders nicely in GitLab, with organized markdown (use code blocks if needed), and send only the review content. Include short question labels so each answer section is easy to identify.'
}]

export const AI_MODEL_TEMPERATURE = 0.2

export interface BuildPromptParameters {
  oldFiles?: OldFileVersion[]
  changes: Array<{ diff: string }>
  limits?: Partial<PromptLimits>

}
export const buildPrompt = ({ changes, oldFiles, limits }: BuildPromptParameters): ChatCompletionMessageParam[] => {
  const effectiveLimits: PromptLimits = {
    ...DEFAULT_PROMPT_LIMITS,
    ...(limits ?? {})
  }
  const oldFilesTrimmed = (oldFiles ?? [])
    .slice(0, effectiveLimits.maxOldFiles)
    .map((oldFile) => ({
      fileName: oldFile.fileName,
      fileContent: truncateWithMarker(oldFile.fileContent, effectiveLimits.maxOldFileChars, `old file "${oldFile.fileName}"`)
    }))
  const diffsTrimmed = changes
    .slice(0, effectiveLimits.maxDiffs)
    .map((change, index) => truncateWithMarker(change.diff, effectiveLimits.maxDiffChars, `diff #${index + 1}`))

  const hasOldFiles = oldFilesTrimmed.length > 0
  const oldFilesText = hasOldFiles ? oldFilesTrimmed.map(oldFile => JSON.stringify(oldFile)).join('\n\n') : '(not provided)'
  const changesText = diffsTrimmed.join('\n\n')

  const content = `
    As a senior developer, review the following code changes and answer code review questions about them. The code changes are provided as git diff strings.
    ${hasOldFiles ? 'The entire file before the change is provided for context. Make sure to keep it as a reference when reviewing the changes.' : 'No full pre-change file context is available; review based on the diff only.'}
    Input safety constraints were applied to keep payload size bounded. If you see truncation markers, call out potential blind spots in your review.

    Files before changes:
    ${oldFilesText}

    Changes:
    ${changesText}

    ${QUESTIONS}
    `

  const boundedContent = truncateWithMarker(content, effectiveLimits.maxTotalPromptChars, 'prompt payload')
  return [...MESSAGES, { role: 'user', content: boundedContent }]
}

const ERROR_ANSWER = 'I\'m sorry, I\'m not feeling well today. Please ask a human to review this code change.'

const DISCLAIMER = 'This comment was generated by an artificial intelligence duck.'

function sanitizeGitLabMarkdown (input: string): string {
  const normalized = input.replace(/\r\n/g, '\n').trim()
  // If the model forgets to close a fenced code block, GitLab will render the rest (incl. disclaimer) inside it.
  const fenceCount = (normalized.match(/```/g) ?? []).length
  const withClosedFence = fenceCount % 2 === 1 ? `${normalized}\n\`\`\`` : normalized
  return withClosedFence
}

export const buildAnswer = (completion: ChatCompletion | Error | undefined): string => {
  if (completion instanceof Error) {
    const maybeCause = (completion as any).cause
    const causeMessage = maybeCause instanceof Error ? maybeCause.message : undefined
    return `${ERROR_ANSWER}\n\nError: ${completion.message}${causeMessage != null ? `\nCause: ${causeMessage}` : ''}`
  }
  if ((completion == null) || (completion.choices.length === 0)) {
    return `${ERROR_ANSWER}\n\n${DISCLAIMER}`
  }
  const content = completion.choices[0]!.message.content ?? ''
  const safe = sanitizeGitLabMarkdown(content)
  return `${safe}\n\n---\n_${DISCLAIMER}_`
}
